#!/usr/bin/env python3
import sys
sys.path.append("scripts")

from RepeatXuTRACTR import segment_repeat


def show(name, seq):
    print("=" * 80)
    print(name)
    print(f"len={len(seq)}")
    print(segment_repeat(seq)["encodedSeq"])
    print()


def main():

    # 1) FMR1: CGG repeat with AGG interruptions 
    fmr1 = (
        "CGCCGCTGCCAGGGGGCGTGCGGCAGCGCGGCGGCGGCGGCGGCGGCGGCGGCGGAGG"
        "CGGCGGCGGCGGCGGCGGCGGCGGCGGAGGCGGCGGCGGCGGCGGCGGCGGCGGCGG"
        "CTGGGCCTCGAGCGCCCGCAGCCCA"
    )
    show("FMR1 decomposition with no parameters", fmr1)
    from repeat_utils import calculate_lps
    enc = segment_repeat(fmr1)["encodedSeq"]
    print("LPS (longest pure segment in decomposed repeat):", calculate_lps(enc))
    print()


    samd12 = (
        "GGGCAACAAGAGTGAAACTCTGTCTCAAATAAAATAAAATAAAATAAAATATAATA"
        "AAATAAAATAAAATAAAATAAAATAAAATAAAATAAAATAATAAAATAAAATAAAA"
        "TAAAATAAAATAAAATAAAATAAAAATGAACAAAATGAAAAGGGGGATAC"
    )

    print("=" * 80)
    print("SAMD12 (pentanucleotide repeat)")
    print("len =", len(samd12))
    print("default frame:")
    print(segment_repeat(samd12)["encodedSeq"])
    print("reverse=True (max alphabetical frame):")
    print(segment_repeat(samd12, reverse=True)["encodedSeq"])
    print()

    # HTT: CAG trinucleotide expansion
    # Demonstrates:
    # 1) Default behavior (auto-detect kmers, trimEnds=True)
    # 2) setkmers=['CAG'] to force tracking of a specific motif
    # 3) trimEnds=False to allow detection of motifs even if the repeat
    #    does not cleanly end at a repeating boundary

    htt = (
        "AGGCCTTCGAGTCCCTCAAGTCCTTCCAG"
        "CAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAG"
        "CAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAG"
        "CAACAGCCGCCACCGCCGCCGCCGCCGCCGCCGCCGCCGC"
        "CTCCTCCTCAGCTTCCTCAGCCGCCGCCGC"
    )

    print("=" * 80)
    print("HTT (CAG trinucleotide expansion)")
    print("len =", len(htt))

    print("default:")
    print(segment_repeat(htt)["encodedSeq"])

    print("setkmers=['CAG']:")
    print(segment_repeat(htt, setkmers=['CAG'])["encodedSeq"])

    print("setkmers=['CAG'], trimEnds=False:")
    print(segment_repeat(htt, setkmers=['CAG'], trimEnds=False)["encodedSeq"])
    print()

    # HTT: demonstrating include_kmers vs setkmers
    # - setkmers=['CAG'] strictly restricts decomposition to CAG only
    # - include_kmers=['CAG'] *adds* motifs to the candidate set,
    #   but still allows other motifs to be detected if supported by the sequence

    print("include_kmers=['CAG'] (allow additional supported motifs):")
    print(segment_repeat(htt, include_kmers=['CAG', 'CCG'])["encodedSeq"])
    print()


    # RFC1: long noisy (AAAGG/AAGGG-like) expansion with many small interruptions.
    # Demonstrates remove_singletons():
    # - segment_repeat() may output a very long encodedSeq with many tiny, non-dominant motif blocks
    #   (often count=1 artifacts or rare interruptions like <CAG>1, <AG>1, etc.).
    # - remove_singletons() filters out motif blocks that are:
    #     * too small (count < min_count),
    #     * too short (motif length < min_motif_len),
    #     * or contribute too little total bp (< min_bp_prop of total bp),
    #   then merges adjacent identical motifs.
    # Result: a compact summary of the dominant repeat (e.g., "<AAAGG>554") for large alleles.

    from repeat_utils import remove_singletons

    rfc1 = (
        "GGCAACAGAGCAAGACTCTGTTTCAAAACGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGAAAGAGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGAGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGAGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGCAGAAAGGAAAGGAAAGGAAAGCAGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGAGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGCAGAAAGGAAAGGAAAGGAAAGGAAAGAGCAGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGAGCAAAGGAAAGGAAAGGAAAGAGCAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAGAGCAGAGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGCAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGAGAAGAGGAAAGGAAAGGAAAGGAAAGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGCAAAGGAAAGGAAAGCAAAGGAAAGGAAAGGAAAGAGCAAAGGAAAGGAAGCAGAGAAAGGAAAGGAAAGGAAAGGAAGAGCAGAGAAAGGAAAGGAAAGGAAAGCAAAGGAAAGCAAAGGAAAGCAAAGGAAAGCAAAGGAAAGCAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGCAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGCAAGCAGAGAAGAGGAAAGGAAGGAAAGCAGAGAAGAGGAAAGGAAAGGAAGCAGAGAAAGAGGAAAGCAAAGGAAAGGAAAGGAAAGGAGAGCAGAGAAGAGGAAAGGAAAGGAAAGAGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAGCAGAAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAGCAGAGAAGGAAAGGAAAGAGAAGGAAAGGAAAGGAAAGGAAAGCAAAGGAAAGCAGAGCAAGCAGAGCAAGAAGCAGAGCAGAGCAGAGGAGCAGAGCAGAAAGCAGAGGAGCAGAGGAAAGGAGAGCAGAAAGCAGAGCAGAGGAAAGCAGAGAAGCAGAGCAGAGAAGCAGAGAAAGAGAAAGCAGAGCAGAGGAAAGGAAAGGAAAGCAGAGCAGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAAAGGAAAGGAAAGGAAAGGAAAGCAGAAAGGAAAGGAAAGGAGAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAGGAAAAGAAAAGAAAAGAAAAAGCATGTTCTAAAGAGAATAGCAAC"
    )

    print("=" * 80)
    print("RFC1 (noisy long expansion; remove_singletons cleanup)")
    print("len =", len(rfc1))

    raw = segment_repeat(rfc1)["encodedSeq"]
    print("raw encodedSeq (truncated):")
    print((raw[:200] + " ...") if raw else None)

    print("after remove_singletons():")
    print(remove_singletons(raw))
    print()



if __name__ == "__main__":
    main()

